# Feature Engineering

**Objective:** Convert raw images and sales data into a structured feature matrix suitable for regression.

**Inputs:**
- `data/processed/product_summary.csv` — per-product aggregates (146 products)
- `data/processed/images_inventory.csv` — 180 image paths with folder labels

**Outputs:**
- `data/processed/image_embeddings.npy` — ResNet50 embeddings, shape (180, 2048)
- `data/processed/training_set.csv` — final feature table with targets

**Sections:**
1. Load processed data
2. Image–product mapping (stratified random assignment)
3. ResNet50 embedding extraction
4. Assemble final training set

In [1]:
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

PROJECT_ROOT = Path('..').resolve()
sys.path.append(str(PROJECT_ROOT))

from src.feature_extractor import load_resnet50_extractor, extract_embeddings

PROCESSED = PROJECT_ROOT / 'data' / 'processed'
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Device:', device)

Device: cpu


## 1. Load processed data

In [2]:
products = pd.read_csv(PROCESSED / 'product_summary.csv')
images = pd.read_csv(PROCESSED / 'images_inventory.csv')

print('Products :', len(products))
print('Images   :', len(images))
print('\nProducts head:')
print(products[['code', 'total_qty', 'transactions', 'avg_rate']].head())
print('\nImages head:')
print(images.head())

Products : 146
Images   : 180

Products head:
       code  total_qty  transactions     avg_rate
0    500001       1032            57  1295.017544
1  10016728         24             6   875.000000
2  10019275         56            13  1650.000000
3  10021130         32             7   875.000000
4  10021131         28             6   875.000000

Images head:
   folder                                          filename  \
0       1      WhatsApp Image 2026-04-29 at 1.26.56 PM.jpeg   
1       1  WhatsApp Image 2026-04-29 at 1.26.57 PM (1).jpeg   
2       1      WhatsApp Image 2026-04-29 at 1.26.57 PM.jpeg   
3       1  WhatsApp Image 2026-04-29 at 1.26.58 PM (1).jpeg   
4       1      WhatsApp Image 2026-04-29 at 1.26.58 PM.jpeg   

                                                path  size_kb  
0  E:\POC\project-poc\data\raw\images\1\WhatsApp ...    424.0  
1  E:\POC\project-poc\data\raw\images\1\WhatsApp ...    444.2  
2  E:\POC\project-poc\data\raw\images\1\WhatsApp ...    423.1  
3  E:

## 2. Image–product mapping (stratified random assignment)

**Assumption:** Because filenames do not encode product codes and the four folders do not map to code prefixes, we cannot recover a one-to-one image-to-product mapping from the available data. We therefore generate a *stratified synthetic mapping*:

- Each image is randomly assigned a product code drawn from the full product pool.
- Sampling is performed with replacement (180 images, 146 products).
- The random seed is fixed for reproducibility.
- Folder identity is preserved as a categorical feature and exposes any folder-level demand signal to the model.

**Honest implication:** If image features carry genuine demand signal, the model will learn it and outperform the folder-only baseline. If not, predictions will collapse to folder-level averages — an outcome we will report transparently.

In [3]:
rng = np.random.default_rng(RANDOM_SEED)
assigned_codes = rng.choice(products['code'].values, size=len(images), replace=True)

mapping = images.copy()
mapping['assigned_code'] = assigned_codes
mapping = mapping.merge(
    products[['code', 'total_qty', 'avg_rate', 'transactions']],
    left_on='assigned_code', right_on='code', how='left'
).drop(columns=['code'])

print('Mapping shape:', mapping.shape)
print('Unique codes used :', mapping['assigned_code'].nunique(), 'of', len(products))
print('\nTarget summary (total_qty):')
print(mapping['total_qty'].describe().round(2))
mapping.head()

Mapping shape: (180, 8)
Unique codes used : 100 of 146

Target summary (total_qty):
count    180.00
mean      19.58
std       18.28
min        3.00
25%        8.00
50%       12.00
75%       24.00
max      110.00
Name: total_qty, dtype: float64


,folder,filename,path,size_kb,assigned_code,total_qty,avg_rate,transactions
0,1,WhatsApp Image 2026-04-29 at 1.26.56 PM.jpeg,E:\POC\project-poc\data\raw\images\1\WhatsApp ...,424.0,10027276,12,525.0,3
1,1,WhatsApp Image 2026-04-29 at 1.26.57 PM (1).jpeg,E:\POC\project-poc\data\raw\images\1\WhatsApp ...,444.2,10029305,8,725.0,1
2,1,WhatsApp Image 2026-04-29 at 1.26.57 PM.jpeg,E:\POC\project-poc\data\raw\images\1\WhatsApp ...,423.1,10029229,13,750.0,3
3,1,WhatsApp Image 2026-04-29 at 1.26.58 PM (1).jpeg,E:\POC\project-poc\data\raw\images\1\WhatsApp ...,421.7,10028755,21,550.0,5
4,1,WhatsApp Image 2026-04-29 at 1.26.58 PM.jpeg,E:\POC\project-poc\data\raw\images\1\WhatsApp ...,378.5,10028754,16,550.0,5


In [4]:
print('Folder-wise target distribution after mapping:')
folder_stats = mapping.groupby('folder').agg(
    n_images=('filename', 'size'),
    mean_qty=('total_qty', 'mean'),
    median_qty=('total_qty', 'median'),
    std_qty=('total_qty', 'std'),
    mean_rate=('avg_rate', 'mean'),
).round(2)
folder_stats

Folder-wise target distribution after mapping:


,n_images,mean_qty,median_qty,std_qty,mean_rate
folder,,,,,
1,55,16.31,12.0,14.57,856.10
2,52,19.77,12.0,16.62,869.52
3,36,21.06,18.0,18.30,877.92
4,37,22.73,12.0,24.44,897.70


## 3. ResNet50 embedding extraction

We use ImageNet-pretrained ResNet50 with the final classification layer replaced by identity. Each image is preprocessed (resize 256, centre-crop 224, ImageNet normalisation) and passed through the network. The 2048-dimensional global-average-pooled output forms the visual representation.

In [5]:
model = load_resnet50_extractor(device=device)
print('Model loaded. Parameters:', sum(p.numel() for p in model.parameters()))
print('Output layer:', model.fc)

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to C:\Users\praveen/.cache\torch\hub\checkpoints\resnet50-11ad3fa6.pth


0.1%

0.3%

0.4%

0.5%

0.6%

0.8%

0.9%

1.0%

1.2%

1.3%

1.4%

1.5%

1.7%

1.8%

1.9%

2.0%

2.2%

2.3%

2.4%

2.6%

2.7%

2.8%

2.9%

3.1%

3.2%

3.3%

3.5%

3.6%

3.7%

3.8%

4.0%

4.1%

4.2%

4.3%

4.5%

4.6%

4.7%

4.9%

5.0%

5.1%

5.2%

5.4%

5.5%

5.6%

5.8%

5.9%

6.0%

6.1%

6.3%

6.4%

6.5%

6.6%

6.8%

6.9%

7.0%

7.2%

7.3%

7.4%

7.5%

7.7%

7.8%

7.9%

8.1%

8.2%

8.3%

8.4%

8.6%

8.7%

8.8%

8.9%

9.1%

9.2%

9.3%

9.5%

9.6%

9.7%

9.8%

10.0%

10.1%

10.2%

10.4%

10.5%

10.6%

10.7%

10.9%

11.0%

11.1%

11.2%

11.4%

11.5%

11.6%

11.8%

11.9%

12.0%

12.1%

12.3%

12.4%

12.5%

12.7%

12.8%

12.9%

13.0%

13.2%

13.3%

13.4%

13.5%

13.7%

13.8%

13.9%

14.1%

14.2%

14.3%

14.4%

14.6%

14.7%

14.8%

15.0%

15.1%

15.2%

15.3%

15.5%

15.6%

15.7%

15.9%

16.0%

16.1%

16.2%

16.4%

16.5%

16.6%

16.7%

16.9%

17.0%

17.1%

17.3%

17.4%

17.5%

17.6%

17.8%

17.9%

18.0%

18.2%

18.3%

18.4%

18.5%

18.7%

18.8%

18.9%

19.0%

19.2%

19.3%

19.4%

19.6%

19.7%

19.8%

19.9%

20.1%

20.2%

20.3%

20.5%

20.6%

20.7%

20.8%

21.0%

21.1%

21.2%

21.3%

21.5%

21.6%

21.7%

21.9%

22.0%

22.1%

22.2%

22.4%

22.5%

22.6%

22.8%

22.9%

23.0%

23.1%

23.3%

23.4%

23.5%

23.6%

23.8%

23.9%

24.0%

24.2%

24.3%

24.4%

24.5%

24.7%

24.8%

24.9%

25.1%

25.2%

25.3%

25.4%

25.6%

25.7%

25.8%

25.9%

26.1%

26.2%

26.3%

26.5%

26.6%

26.7%

26.8%

27.0%

27.1%

27.2%

27.4%

27.5%

27.6%

27.7%

27.9%

28.0%

28.1%

28.2%

28.4%

28.5%

28.6%

28.8%

28.9%

29.0%

29.1%

29.3%

29.4%

29.5%

29.7%

29.8%

29.9%

30.0%

30.2%

30.3%

30.4%

30.6%

30.7%

30.8%

30.9%

31.1%

31.2%

31.3%

31.4%

31.6%

31.7%

31.8%

32.0%

32.1%

32.2%

32.3%

32.5%

32.6%

32.7%

32.9%

33.0%

33.1%

33.2%

33.4%

33.5%

33.6%

33.7%

33.9%

34.0%

34.1%

34.3%

34.4%

34.5%

34.6%

34.8%

34.9%

35.0%

35.2%

35.3%

35.4%

35.5%

35.7%

35.8%

35.9%

36.0%

36.2%

36.3%

36.4%

36.6%

36.7%

36.8%

36.9%

37.1%

37.2%

37.3%

37.5%

37.6%

37.7%

37.8%

38.0%

38.1%

38.2%

38.3%

38.5%

38.6%

38.7%

38.9%

39.0%

39.1%

39.2%

39.4%

39.5%

39.6%

39.8%

39.9%

40.0%

40.1%

40.3%

40.4%

40.5%

40.6%

40.8%

40.9%

41.0%

41.2%

41.3%

41.4%

41.5%

41.7%

41.8%

41.9%

42.1%

42.2%

42.3%

42.4%

42.6%

42.7%

42.8%

42.9%

43.1%

43.2%

43.3%

43.5%

43.6%

43.7%

43.8%

44.0%

44.1%

44.2%

44.4%

44.5%

44.6%

44.7%

44.9%

45.0%

45.1%

45.2%

45.4%

45.5%

45.6%

45.8%

45.9%

46.0%

46.1%

46.3%

46.4%

46.5%

46.7%

46.8%

46.9%

47.0%

47.2%

47.3%

47.4%

47.6%

47.7%

47.8%

47.9%

48.1%

48.2%

48.3%

48.4%

48.6%

48.7%

48.8%

49.0%

49.1%

49.2%

49.3%

49.5%

49.6%

49.7%

49.9%

50.0%

50.1%

50.2%

50.4%

50.5%

50.6%

50.7%

50.9%

51.0%

51.1%

51.3%

51.4%

51.5%

51.6%

51.8%

51.9%

52.0%

52.2%

52.3%

52.4%

52.5%

52.7%

52.8%

52.9%

53.0%

53.2%

53.3%

53.4%

53.6%

53.7%

53.8%

53.9%

54.1%

54.2%

54.3%

54.5%

54.6%

54.7%

54.8%

55.0%

55.1%

55.2%

55.3%

55.5%

55.6%

55.7%

55.9%

56.0%

56.1%

56.2%

56.4%

56.5%

56.6%

56.8%

56.9%

57.0%

57.1%

57.3%

57.4%

57.5%

57.6%

57.8%

57.9%

58.0%

58.2%

58.3%

58.4%

58.5%

58.7%

58.8%

58.9%

59.1%

59.2%

59.3%

59.4%

59.6%

59.7%

59.8%

59.9%

60.1%

60.2%

60.3%

60.5%

60.6%

60.7%

60.8%

61.0%

61.1%

61.2%

61.4%

61.5%

61.6%

61.7%

61.9%

62.0%

62.1%

62.3%

62.4%

62.5%

62.6%

62.8%

62.9%

63.0%

63.1%

63.3%

63.4%

63.5%

63.7%

63.8%

63.9%

64.0%

64.2%

64.3%

64.4%

64.6%

64.7%

64.8%

64.9%

65.1%

65.2%

65.3%

65.4%

65.6%

65.7%

65.8%

66.0%

66.1%

66.2%

66.3%

66.5%

66.6%

66.7%

66.9%

67.0%

67.1%

67.2%

67.4%

67.5%

67.6%

67.7%

67.9%

68.0%

68.1%

68.3%

68.4%

68.5%

68.6%

68.8%

68.9%

69.0%

69.2%

69.3%

69.4%

69.5%

69.7%

69.8%

69.9%

70.0%

70.2%

70.3%

70.4%

70.6%

70.7%

70.8%

70.9%

71.1%

71.2%

71.3%

71.5%

71.6%

71.7%

71.8%

72.0%

72.1%

72.2%

72.3%

72.5%

72.6%

72.7%

72.9%

73.0%

73.1%

73.2%

73.4%

73.5%

73.6%

73.8%

73.9%

74.0%

74.1%

74.3%

74.4%

74.5%

74.6%

74.8%

74.9%

75.0%

75.2%

75.3%

75.4%

75.5%

75.7%

75.8%

75.9%

76.1%

76.2%

76.3%

76.4%

76.6%

76.7%

76.8%

77.0%

77.1%

77.2%

77.3%

77.5%

77.6%

77.7%

77.8%

78.0%

78.1%

78.2%

78.4%

78.5%

78.6%

78.7%

78.9%

79.0%

79.1%

79.3%

79.4%

79.5%

79.6%

79.8%

79.9%

80.0%

80.1%

80.3%

80.4%

80.5%

80.7%

80.8%

80.9%

81.0%

81.2%

81.3%

81.4%

81.6%

81.7%

81.8%

81.9%

82.1%

82.2%

82.3%

82.4%

82.6%

82.7%

82.8%

83.0%

83.1%

83.2%

83.3%

83.5%

83.6%

83.7%

83.9%

84.0%

84.1%

84.2%

84.4%

84.5%

84.6%

84.7%

84.9%

85.0%

85.1%

85.3%

85.4%

85.5%

85.6%

85.8%

85.9%

86.0%

86.2%

86.3%

86.4%

86.5%

86.7%

86.8%

86.9%

87.0%

87.2%

87.3%

87.4%

87.6%

87.7%

87.8%

87.9%

88.1%

88.2%

88.3%

88.5%

88.6%

88.7%

88.8%

89.0%

89.1%

89.2%

89.3%

89.5%

89.6%

89.7%

89.9%

90.0%

90.1%

90.2%

90.4%

90.5%

90.6%

90.8%

90.9%

91.0%

91.1%

91.3%

91.4%

91.5%

91.7%

91.8%

91.9%

92.0%

92.2%

92.3%

92.4%

92.5%

92.7%

92.8%

92.9%

93.1%

93.2%

93.3%

93.4%

93.6%

93.7%

93.8%

94.0%

94.1%

94.2%

94.3%

94.5%

94.6%

94.7%

94.8%

95.0%

95.1%

95.2%

95.4%

95.5%

95.6%

95.7%

95.9%

96.0%

96.1%

96.3%

96.4%

96.5%

96.6%

96.8%

96.9%

97.0%

97.1%

97.3%

97.4%

97.5%

97.7%

97.8%

97.9%

98.0%

98.2%

98.3%

98.4%

98.6%

98.7%

98.8%

98.9%

99.1%

99.2%

99.3%

99.4%

99.6%

99.7%

99.8%

100.0%

100.0%

Model loaded. Parameters: 23508032
Output layer: Identity()


In [6]:
import time

image_paths = mapping['path'].tolist()
start = time.time()
embeddings = extract_embeddings(image_paths, model=model, device=device, batch_size=16)
elapsed = time.time() - start

print(f'Extracted embeddings : {embeddings.shape}')
print(f'Time taken           : {elapsed:.1f} seconds ({elapsed/len(image_paths):.2f} s/image)')
print(f'Embedding dtype      : {embeddings.dtype}')
print(f'Embedding range      : [{embeddings.min():.3f}, {embeddings.max():.3f}]')

Extracted embeddings : (180, 2048)
Time taken           : 49.8 seconds (0.28 s/image)
Embedding dtype      : float32
Embedding range      : [0.000, 7.160]


In [7]:
np.save(PROCESSED / 'image_embeddings.npy', embeddings)
print('Saved:', PROCESSED / 'image_embeddings.npy')

Saved: E:\POC\project-poc\data\processed\image_embeddings.npy


## 4. Assemble final training set

The final feature matrix combines:
- 2048 image embedding dimensions (from ResNet50)
- 1 numerical feature: average rate of the assigned product
- 4 one-hot encoded folder indicators

Total feature dimensionality: 2053. Target: total quantity sold for the assigned product.

In [8]:
folder_onehot = pd.get_dummies(mapping['folder'].astype(str), prefix='folder').astype(int)
tabular = pd.concat([
    mapping[['assigned_code', 'total_qty', 'avg_rate']].reset_index(drop=True),
    folder_onehot.reset_index(drop=True)
], axis=1)
tabular.head()

,assigned_code,total_qty,avg_rate,folder_1,folder_2,folder_3,folder_4
0,10027276,12,525.0,1,0,0,0
1,10029305,8,725.0,1,0,0,0
2,10029229,13,750.0,1,0,0,0
3,10028755,21,550.0,1,0,0,0
4,10028754,16,550.0,1,0,0,0


In [9]:
embedding_cols = [f'emb_{i}' for i in range(embeddings.shape[1])]
embeddings_df = pd.DataFrame(embeddings, columns=embedding_cols)

training_set = pd.concat([
    mapping[['filename', 'folder', 'path', 'assigned_code']].reset_index(drop=True),
    embeddings_df.reset_index(drop=True),
    mapping[['avg_rate', 'total_qty']].reset_index(drop=True),
    folder_onehot.reset_index(drop=True),
], axis=1)

training_set.to_csv(PROCESSED / 'training_set.csv', index=False)
print('Training set shape :', training_set.shape)
print('Saved              :', PROCESSED / 'training_set.csv')
print('\nColumns (preview):')
print(list(training_set.columns[:5]) + ['...'] + list(training_set.columns[-6:]))

Training set shape : (180, 2058)
Saved              : E:\POC\project-poc\data\processed\training_set.csv

Columns (preview):
['filename', 'folder', 'path', 'assigned_code', 'emb_0', '...', 'avg_rate', 'total_qty', 'folder_1', 'folder_2', 'folder_3', 'folder_4']


In [10]:
feature_cols = embedding_cols + ['avg_rate'] + list(folder_onehot.columns)
target_col = 'total_qty'
print('Feature dimensionality :', len(feature_cols))
print('Target column          :', target_col)
print('Sample rows            :', len(training_set))
print('\nReady for Phase 3 (model training).')

Feature dimensionality : 2053
Target column          : total_qty
Sample rows            : 180

Ready for Phase 3 (model training).
